spring:
  application:
    name: catalog-service
  cloud:
    config:
      uri:
      - http://localhost:8888
---
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecomappProductshop     